### PR TITLE
[WIP] Add carthage support for iOS

### PR DESCRIPTION
**Pull request by roccx**
Add framework project for iOS, see issue #4 

Note:
The framework [ReachabilitySwift](https://github.com/ashleymills/Reachability.swift) has a [module name issue](https://github.com/ashleymills/Reachability.swift/issues/128) which requires a workaround to enable cross compatibility for cocoapods and carthage.
 
TODO:
- Add framework targets for all supported platforms
- Find a solution for the breaking import changes to support cocoapods

### CODE REVIEW

**Comment by arsen-vartbaronov** [comment]
Hi, m-ylmz

Currently if I merge this change SDK isn't to compile due to "no such module 'Reachability'" error. 
Is it expected? 
Is it because of "Find a solution for the breaking import changes to support cocoapods"? 
And if yes what option we have to resolve it?
Can you also remind me what company as our client you represented (if any)?

**Comment by roccx** [comment]
The Reachability Framework has two different names for Carthage and CocoaPods. Thats the reason why you get an error when you try to compile. We are working for a client, so I'm not able to tell you any company informations where we use your service. 
I had only time to fix the issues so that is works in our project with Carthage. It is not a complete solution but could be completed.
You could fork the Reachability framework by fixing the problem or maybe find another solution for it.

**Comment by Dschee** [comment]
@arsen-vartbaronov Please refer to https://github.com/Daltron/NotificationBanner/pull/5 where we had the same issue with a dependency named MarqueeLabel and it was solved by adding a `CARTHAGE_CONFIG` Swift flag (see [this PR](https://github.com/Dschee/NotificationBanner/pull/1) to my PR). That solution might work here as well.

**Comment by olebahlmann** [comment]
Thanks @roccx, @Dschee for you contributions

I added this topic to our backlog and we will be working on it.
I'll update this PR upon further development.

**Pull request merged**
