### PR TITLE
Xcode 9 support

### LINKED ISSUE #21: Xcode 9 support – CryptoSwift dependency too strict
Xcode 9 GM seed was released yesterday. Developers are expected to use Xcode 9 from now on, but the CryptoSwift version is defined way too strict in the Cartfile. It should better be `~> 0.7` instead of the very restrictive `== 0.6.9` which is not a good idea, especially for a framework.

### PR DESCRIPTION
**Pull request by Dschee**
Fixes #21 and #23.

### CODE REVIEW

**Comment by Dschee** [comment]
I've just tested this and can confirm that it works for us with Xcode 9 GM seed + Carthage 0.24.0.

**Comment by arsen-vartbaronov** [comment]
@Dschee per Semantic Version documentation:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
That means that CryptoSwift can do any change, including not backward compatible. In that case SDK might stop to compile because of unexpected change. 
The good news is that now we remove dependency from CryptoSwift and the only thing we need to do just remove it from Cartfile and test projects. 
This one I has been done in another pull request

**Comment by arsen-vartbaronov** [comment]
@Dschee I closed this request, because I have done some other works, with completely removing dependency on CryptoSwift. Please check if it is OK for you.

**Comment by Dschee** [comment]
I don't care how you solve them, but as long as you solve #21 and #23 I'm gonna be happy. :)
For now I will continue using my fork as it works.

**Pull request closed without merging**
