### PR TITLE
Fixed for swift 5.0

### PR DESCRIPTION
**Pull request by matteomatassoni**
I've checked your master and resolved few issues and warning with Xcode 10.2 and Swift 5.0

### CODE REVIEW

**Comment by MBing** [comment]
Hi @matteomatassoni ,
thanks for this!
Is this the migration from Xcode or something you did specifically?

Did you test the behavior for these changes? If everything still works as before?

**Comment by MBing** [comment]
Unfortunately there are quite some changes in here that would break the code on all of our current (using version 4 of the SDK) clients. I did the migrate as I assume you did and fixed some other errors. I will update it soon here and deploy a new version. Thanks for the efforts!

If you have any questions, let me know of course and I am glad to explain.

**Comment by matteomatassoni** [comment]
I used the Xcode migration assistant and fixed the remaining warning by myself.

**Comment by MBing** [comment]
The problem is that the behavior changes, when you remove the default `nil` in a lot of parameters, then our other clients implementations will break upon updating. This was added as those params are optional, but the person who made this sdk in the start did not choose them to be optional. So a lot of clients first had to circumvent this by adding empty data structures. Which creates extra complexity for them and this is why it might look uglier for the sdk, but more useful for implementing for the client.

**Pull request closed without merging**
